Part 5
mgrigoriev/ask-and-hack pull request #3
Opened 2016-10-17 22:14 UTC by mgrigoriev

2016-10-18 09:55 UTC, vkurennov requested changes
Исправь замечания

2016-10-18 09:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @question.reload
А зачем перегружать вопрос? Чтобы несохраненный ответ не показывать? Тогда на уровне вида лучше встроить проверку на `persisted?`  для ответов, чтобы показывать  только те, что в базе сохранены и не делать лишнего запроса.

2016-10-18 09:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
Здесь у тебя лишний запрос: ты тянешь юзера у ответа из базы, а ведь, чтобы проверить автора, достаточно сравнить id. @answer.user_id не делает лишнего запроса к базе, т.к. это атрибут самого ответа и он уже загружен в память

2016-10-18 09:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to question_path @answer.question
Можно короче написать: `redirect_to @answer.question`

2016-10-18 09:55 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Опять же, нужно сравнивать по id. И т.к. такая проверка встретится еще не раз, то вынеси ее в метод модели User, чтобы вызывать так: `current_user.author_of?(@question)`.  И не забудь тесты модели написать на этот метод

2016-10-18 09:55 UTC, vkurennov commented on app/views/questions/index.html.slim
> +- if not @questions.empty?
Не используй not, and, or и т.п. для логических выражений, у них самый низкий приоритет выполнения, это может привести к сложновыявимым багам. Используй всегда операторы !, &&, || и т.п.

2016-10-18 09:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user == @question.user
Замени на вызов `User#author_of?`

2016-10-18 09:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if not @question.answers.empty?
Используй ! вместо not

2016-10-18 09:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        - if current_user == answer.user
Замени на вызов `User#author_of?`

2016-10-18 09:55 UTC, vkurennov commented on app/views/shared/_error_messages.html.slim
> +- if target and target.errors.any?
Используй && вместо and

2016-10-18 09:55 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
Здесь нужен тест, проверяющий связь созданного ответа с залогиненным юзером

2016-10-18 09:55 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Нужен тест на связь созданного вопроса с залогиненным юзером

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/answers/create_answer_spec.rb
> +    visit question_path create(:question)
Заключай в скобки параметры question_path, это лучше читается.

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/answers/create_answer_spec.rb
> +  scenario 'Non-authenticated user tries to create answer' do
Нужен еще сценарий на ошибки, т.е. не нужно проверять все валидации (это мы делаем в модели), а надо проверить, что система сообщила пользователю об ошибке.

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/answers/delete_answer_spec.rb
> +    expect(page).to have_content 'Answer deleted successfully'
Надо проверить, что на странице больше нет текста ответа

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/answers/delete_answer_spec.rb
> +  scenario 'Non-author tries to delete the question' do
И еще нужен сценарий, когда незалогиненный юзер не видит ссылку

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/questions/create_question_spec.rb
> +    expect(page).to have_css '.error_explanation'
Не надо проверять классы, и вообще привязываться к верстке, насколько это возможно. Верстка может поменяться, и нужно будет менять тесты. Да и наличие классов никак не доказывает, что юзер увидел ошибку. 
Вообще, acceptance-тесты пишутся как для живых тестеров. Ты же не напишешь живому тестеру: "нажми submit, затем открой исходник страницы и проверь наличие таких-то классов". Надо проверять то, что видит пользователь.

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/questions/delete_question_spec.rb
> +    expect(page).to have_content 'Question deleted successfully'
Надо проверить, что на странице больше нет вопроса

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/questions/delete_question_spec.rb
> +  scenario 'Non-author tries to delete the question' do
Нужен аналогичный тест для незалогиненного юзера

2016-10-18 09:55 UTC, vkurennov commented on spec/feature/questions/read_question_spec.rb
> +        expect(page).to have_content answer.body
Делай отступ в блоке

2016-10-18 19:02 UTC, vkurennov approved these changes
Принято, но исправь замечания

2016-10-18 19:02 UTC, vkurennov commented on app/models/user.rb
> +    if (resource.instance_of? Question) || (resource.instance_of? Answer)
А зачем делать ограничение на тип? Пусть метод будет универсальным, и работает для любого объекта

2016-10-18 19:02 UTC, vkurennov commented on app/models/user.rb
> +        return true
Сравнение - это операция, которая возвращает результат, т.е. `resource.user_id == id` и так вернет true/false, никаких if и return не нужно, если это одна строка в методе

2016-10-18 19:02 UTC, vkurennov commented on spec/models/user_spec.rb
> +      it { expect(author.author_of?(question)).to be_truthy }
Для методов-предикатов (на знак вопроса заканичваются), если одна фишка в rspec, их можно как матчеры использовать: `expect(author).to be_author_of(question)`
Т.е. добавляешь be_ и убираешь знак вопроса и можно использовать после to и to_not

2016-10-20 10:41 UTC, mgrigoriev commented
Squashed and merged to master via command line

2016-10-20 10:41 UTC, closed without merging